export enum AdminActions {
    NEXT_QUESTION = 'NEXT_QUESTION',
    SKIP_COUNTDOWN = 'SKIP_COUNTDOWN',
    GO_TO_ANSWER = 'GO_TO_ANSWER',
    GO_TO_FINAL_RESULTS = 'GO_TO_FINAL_RESULTS',
    END = 'END'
}
